export const Q_TRANSFERENCIAS = `
SELECT
  t.TRANSACAO,
  CASE
    WHEN t.CODFILIALORIG IN (1, 5, 11, 17, 51) THEN 'GOIÂNIA, GO'
    WHEN t.CODFILIALORIG IN (2, 15, 21, 75)    THEN 'BRASÍLIA, DF'
    WHEN t.CODFILIALORIG IN (4, 14, 41, 74)    THEN 'UBERLÂNDIA, MG'
    WHEN t.CODFILIALORIG IN (7, 71)            THEN 'BELO HORIZONTE, MG'
    WHEN t.CODFILIALORIG IN (10, 13, 62, 73)   THEN 'SÃO PAULO, SP'
    WHEN t.CODFILIALORIG IN (3, 16, 31, 76)    THEN 'RIO DE JANEIRO, RJ'
    WHEN t.CODFILIALORIG IN (12, 72)           THEN 'CURITIBA, PR'
    WHEN t.CODFILIALORIG IN (8, 81)            THEN 'PORTO ALEGRE, RS'
    WHEN t.CODFILIALORIG = 20                  THEN 'VALPARAÍSO, GO'
    WHEN t.CODFILIALORIG = 22                  THEN 'CAMPINAS, SP'
    WHEN t.CODFILIALORIG = 25                  THEN 'SERRA, ES'
    WHEN t.CODFILIALORIG = 26                  THEN 'PALHOÇA, SC'
    ELSE TO_CHAR(t.CODFILIALORIG)
  END AS ORIGEM,
  CASE
    WHEN t.CODFILIALDEST IN (1, 5, 11, 17, 51) THEN 'GOIÂNIA, GO'
    WHEN t.CODFILIALDEST IN (2, 15, 21, 75)    THEN 'BRASÍLIA, DF'
    WHEN t.CODFILIALDEST IN (4, 14, 41, 74)    THEN 'UBERLÂNDIA, MG'
    WHEN t.CODFILIALDEST IN (7, 71)            THEN 'BELO HORIZONTE, MG'
    WHEN t.CODFILIALDEST IN (10, 13, 62, 73)   THEN 'SÃO PAULO, SP'
    WHEN t.CODFILIALDEST IN (3, 16, 31, 76)    THEN 'RIO DE JANEIRO, RJ'
    WHEN t.CODFILIALDEST IN (12, 72)           THEN 'CURITIBA, PR'
    WHEN t.CODFILIALDEST IN (8, 81)            THEN 'PORTO ALEGRE, RS'
    WHEN t.CODFILIALDEST = 20                  THEN 'VALPARAÍSO, GO'
    WHEN t.CODFILIALDEST = 22                  THEN 'CAMPINAS, SP'
    WHEN t.CODFILIALDEST = 25                  THEN 'SERRA, ES'
    WHEN t.CODFILIALDEST = 26                  THEN 'PALHOÇA, SC'
    ELSE TO_CHAR(t.CODFILIALDEST)
  END AS DESTINO,
  t.TRANSFESTOQUE                                  AS TRANSF_GERENCIAL,
  t.DATA                                           AS DATA_SOLICITACAO,
  e.nome_guerra || ' (' || t.CODFUNC || ')'        AS SOLICITANTE,
  CASE t.POSICAO
    WHEN 'L' THEN '1/5 TRANSFERENCIA CRIADA'
    WHEN 'E' THEN '2/5 EM COLETA'
    WHEN 'C' THEN '3/5 EM CONFERENCIA'
    WHEN 'V' THEN '4/5 EM ROTA'
    WHEN 'T' THEN '5/5 CONCLUIDA'
    WHEN 'N' THEN 'CANCELADA'
    ELSE 'VERIFICAR'
  END AS STATUS_POSICAO,
  t.POSICAO                                        AS POSICAO_COD,
  t.DATAPOSICAO                                    AS DATA_ATUALIZACAO,
  d.nome_guerra || ' (' || t.CODFUNCPOSICAO || ')' AS FUNC_ATUALIZACAO
FROM WINDOW.TAB_CONTROLE_TRANSF t
LEFT JOIN WINDOW.PCEMPR d ON d.matricula = t.codfuncposicao
LEFT JOIN WINDOW.PCEMPR e ON e.matricula = t.codfunc
WHERE t.TRANSACAO >= 1442
ORDER BY t.DATA DESC
FETCH FIRST 500 ROWS ONLY
`;

export const Q_TRANSFERENCIA_BY_ID = `
SELECT
  t.TRANSACAO,
  CASE
    WHEN t.CODFILIALORIG IN (1, 5, 11, 17, 51) THEN 'GOIÂNIA, GO'
    WHEN t.CODFILIALORIG IN (2, 15, 21, 75)    THEN 'BRASÍLIA, DF'
    WHEN t.CODFILIALORIG IN (4, 14, 41, 74)    THEN 'UBERLÂNDIA, MG'
    WHEN t.CODFILIALORIG IN (7, 71)            THEN 'BELO HORIZONTE, MG'
    WHEN t.CODFILIALORIG IN (10, 13, 62, 73)   THEN 'SÃO PAULO, SP'
    WHEN t.CODFILIALORIG IN (3, 16, 31, 76)    THEN 'RIO DE JANEIRO, RJ'
    WHEN t.CODFILIALORIG IN (12, 72)           THEN 'CURITIBA, PR'
    WHEN t.CODFILIALORIG IN (8, 81)            THEN 'PORTO ALEGRE, RS'
    WHEN t.CODFILIALORIG = 20                  THEN 'VALPARAÍSO, GO'
    WHEN t.CODFILIALORIG = 22                  THEN 'CAMPINAS, SP'
    WHEN t.CODFILIALORIG = 25                  THEN 'SERRA, ES'
    WHEN t.CODFILIALORIG = 26                  THEN 'PALHOÇA, SC'
    ELSE TO_CHAR(t.CODFILIALORIG)
  END AS ORIGEM,
  CASE
    WHEN t.CODFILIALDEST IN (1, 5, 11, 17, 51) THEN 'GOIÂNIA, GO'
    WHEN t.CODFILIALDEST IN (2, 15, 21, 75)    THEN 'BRASÍLIA, DF'
    WHEN t.CODFILIALDEST IN (4, 14, 41, 74)    THEN 'UBERLÂNDIA, MG'
    WHEN t.CODFILIALDEST IN (7, 71)            THEN 'BELO HORIZONTE, MG'
    WHEN t.CODFILIALDEST IN (10, 13, 62, 73)   THEN 'SÃO PAULO, SP'
    WHEN t.CODFILIALDEST IN (3, 16, 31, 76)    THEN 'RIO DE JANEIRO, RJ'
    WHEN t.CODFILIALDEST IN (12, 72)           THEN 'CURITIBA, PR'
    WHEN t.CODFILIALDEST IN (8, 81)            THEN 'PORTO ALEGRE, RS'
    WHEN t.CODFILIALDEST = 20                  THEN 'VALPARAÍSO, GO'
    WHEN t.CODFILIALDEST = 22                  THEN 'CAMPINAS, SP'
    WHEN t.CODFILIALDEST = 25                  THEN 'SERRA, ES'
    WHEN t.CODFILIALDEST = 26                  THEN 'PALHOÇA, SC'
    ELSE TO_CHAR(t.CODFILIALDEST)
  END AS DESTINO,
  t.TRANSFESTOQUE                                  AS TRANSF_GERENCIAL,
  t.DATA                                           AS DATA_SOLICITACAO,
  e.nome_guerra || ' (' || t.CODFUNC || ')'        AS SOLICITANTE,
  CASE t.POSICAO
    WHEN 'L' THEN '1/5 TRANSFERENCIA CRIADA'
    WHEN 'E' THEN '2/5 EM COLETA'
    WHEN 'C' THEN '3/5 EM CONFERENCIA'
    WHEN 'V' THEN '4/5 EM ROTA'
    WHEN 'T' THEN '5/5 CONCLUIDA'
    WHEN 'N' THEN 'CANCELADA'
    ELSE 'VERIFICAR'
  END AS STATUS_POSICAO,
  t.POSICAO                                        AS POSICAO_COD,
  t.DATAPOSICAO                                    AS DATA_ATUALIZACAO,
  d.nome_guerra || ' (' || t.CODFUNCPOSICAO || ')' AS FUNC_ATUALIZACAO
FROM WINDOW.TAB_CONTROLE_TRANSF t
LEFT JOIN WINDOW.PCEMPR d ON d.matricula = t.codfuncposicao
LEFT JOIN WINDOW.PCEMPR e ON e.matricula = t.codfunc
WHERE t.TRANSACAO = :transacao
`;

export const Q_ITENS = `
SELECT
  i.TRANSACAO,
  i.CODPROD,
  p.DESCRICAO AS NOME_PRODUTO,
  i.QUANTIDADE,
  i.SUGESTAO,
  i.DATA,
  i.POSICAO,
  i.QTCOLETADA
FROM WINDOW.TAB_CONTROLE_ITEM_TRANSF i
LEFT JOIN WINDOW.PCPRODUT p ON i.CODPROD = p.CODPROD
WHERE i.TRANSACAO >= 1442
  AND i.TRANSACAO = :transacao
ORDER BY i.CODPROD
`;

export const Q_ETIQUETAS_LIST = `
SELECT
  TRANSACAO,
  CODBARRAS,
  FILIALORIG,
  FILIALDEST,
  DATA,
  CODFUNC,
  CONFIRMADO,
  LEUCODBARRAS,
  CODFUNCLEITURA,
  DATALEITURA,
  PERMITEINCLUIR,
  DATACONFENT,
  CODFUNCCONFENT,
  DATACONFSAI,
  CODFUNCCONFSAI,
  TRANSFESTOQUE,
  VERSAOROTINA,
  CODPROD,
  QUANTIDADE
FROM WINDOW.TAB_TRANSF_ETIQUETA
WHERE TRANSACAO >= 1442
  AND (:codbarras IS NULL OR TO_CHAR(CODBARRAS) LIKE '%' || :codbarras || '%')
ORDER BY CODBARRAS
FETCH FIRST 200 ROWS ONLY
`;

export const Q_ETIQUETA_BY_ITEM = `
SELECT
  TRANSACAO,
  CODBARRAS,
  FILIALORIG,
  FILIALDEST,
  DATA,
  CODFUNC,
  CONFIRMADO,
  LEUCODBARRAS,
  CODFUNCLEITURA,
  DATALEITURA,
  PERMITEINCLUIR,
  DATACONFENT,
  CODFUNCCONFENT,
  DATACONFSAI,
  CODFUNCCONFSAI,
  TRANSFESTOQUE,
  VERSAOROTINA,
  CODPROD,
  QUANTIDADE
FROM WINDOW.TAB_TRANSF_ETIQUETA
WHERE TRANSACAO >= 1442
  AND TRANSACAO = :transacao
  AND CODPROD   = :codprod
ORDER BY CODBARRAS
`;

export const Q_ITENS_SEARCH = `
SELECT
  i.TRANSACAO,
  i.CODPROD,
  p.DESCRICAO AS NOME_PRODUTO,
  i.QUANTIDADE,
  i.QTCOLETADA,
  i.POSICAO AS ITEM_POSICAO,
  t.DATA AS DATA_SOLICITACAO,
  t.POSICAO AS TRANSF_POSICAO,
  CASE
    WHEN t.CODFILIALORIG IN (1, 5, 11, 17, 51) THEN 'GOIÂNIA, GO'
    WHEN t.CODFILIALORIG IN (2, 15, 21, 75)    THEN 'BRASÍLIA, DF'
    WHEN t.CODFILIALORIG IN (4, 14, 41, 74)    THEN 'UBERLÂNDIA, MG'
    WHEN t.CODFILIALORIG IN (7, 71)            THEN 'BELO HORIZONTE, MG'
    WHEN t.CODFILIALORIG IN (10, 13, 62, 73)   THEN 'SÃO PAULO, SP'
    WHEN t.CODFILIALORIG IN (3, 16, 31, 76)    THEN 'RIO DE JANEIRO, RJ'
    WHEN t.CODFILIALORIG IN (12, 72)           THEN 'CURITIBA, PR'
    WHEN t.CODFILIALORIG IN (8, 81)            THEN 'PORTO ALEGRE, RS'
    WHEN t.CODFILIALORIG = 20                  THEN 'VALPARAÍSO, GO'
    WHEN t.CODFILIALORIG = 22                  THEN 'CAMPINAS, SP'
    WHEN t.CODFILIALORIG = 25                  THEN 'SERRA, ES'
    WHEN t.CODFILIALORIG = 26                  THEN 'PALHOÇA, SC'
    ELSE TO_CHAR(t.CODFILIALORIG)
  END AS ORIGEM,
  CASE
    WHEN t.CODFILIALDEST IN (1, 5, 11, 17, 51) THEN 'GOIÂNIA, GO'
    WHEN t.CODFILIALDEST IN (2, 15, 21, 75)    THEN 'BRASÍLIA, DF'
    WHEN t.CODFILIALDEST IN (4, 14, 41, 74)    THEN 'UBERLÂNDIA, MG'
    WHEN t.CODFILIALDEST IN (7, 71)            THEN 'BELO HORIZONTE, MG'
    WHEN t.CODFILIALDEST IN (10, 13, 62, 73)   THEN 'SÃO PAULO, SP'
    WHEN t.CODFILIALDEST IN (3, 16, 31, 76)    THEN 'RIO DE JANEIRO, RJ'
    WHEN t.CODFILIALDEST IN (12, 72)           THEN 'CURITIBA, PR'
    WHEN t.CODFILIALDEST IN (8, 81)            THEN 'PORTO ALEGRE, RS'
    WHEN t.CODFILIALDEST = 20                  THEN 'VALPARAÍSO, GO'
    WHEN t.CODFILIALDEST = 22                  THEN 'CAMPINAS, SP'
    WHEN t.CODFILIALDEST = 25                  THEN 'SERRA, ES'
    WHEN t.CODFILIALDEST = 26                  THEN 'PALHOÇA, SC'
    ELSE TO_CHAR(t.CODFILIALDEST)
  END AS DESTINO
FROM WINDOW.TAB_CONTROLE_ITEM_TRANSF i
LEFT JOIN WINDOW.PCPRODUT p ON i.CODPROD = p.CODPROD
LEFT JOIN WINDOW.TAB_CONTROLE_TRANSF t ON t.TRANSACAO = i.TRANSACAO
WHERE i.TRANSACAO >= 1442
  AND TO_CHAR(i.CODPROD) LIKE '%' || :codprod || '%'
ORDER BY t.DATA DESC NULLS LAST, i.CODPROD
FETCH FIRST 200 ROWS ONLY
`;

export const Q_KPI_STATUS = `
SELECT t.POSICAO, COUNT(*) AS TOTAL
FROM WINDOW.TAB_CONTROLE_TRANSF t
WHERE t.TRANSACAO >= 1442
GROUP BY t.POSICAO
ORDER BY TOTAL DESC
`;

export const Q_KPI_SOLICITANTE = `
SELECT
  e.nome_guerra || ' (' || t.CODFUNC || ')' AS SOLICITANTE,
  COUNT(*) AS TOTAL
FROM WINDOW.TAB_CONTROLE_TRANSF t
LEFT JOIN WINDOW.PCEMPR e ON e.matricula = t.Codfunc
WHERE t.TRANSACAO >= 1442
  AND t.DATA >= SYSDATE - 30
GROUP BY e.nome_guerra || ' (' || t.CODFUNC || ')'
ORDER BY TOTAL DESC
FETCH FIRST 20 ROWS ONLY
`;

export const Q_LEAD_TIMES = `
SELECT
  ROUND(AVG((T_CONFSAI - T_INICIO)  * 24), 2) AS H_SAIDA,
  ROUND(AVG((T_LEITURA - T_CONFSAI) * 24), 2) AS H_ROTA,
  ROUND(AVG((T_CONFENT - T_LEITURA) * 24), 2) AS H_ENTRADA,
  ROUND(AVG((T_CONFENT - T_INICIO)  * 24), 2) AS H_LEAD_TIME,
  COUNT(CASE WHEN T_CONFENT IS NOT NULL THEN 1 END) AS N_CONCLUIDAS,
  COUNT(*) AS N_TOTAL
FROM (
  SELECT
    t.TRANSACAO,
    t.DATA AS T_INICIO,
    MIN(e.DATALEITURA) AS T_LEITURA,
    MIN(e.DATACONFSAI) AS T_CONFSAI,
    MIN(e.DATACONFENT) AS T_CONFENT
  FROM WINDOW.TAB_CONTROLE_TRANSF t
  LEFT JOIN WINDOW.TAB_TRANSF_ETIQUETA e ON e.TRANSACAO = t.TRANSACAO
  WHERE t.TRANSACAO >= 1442
    AND t.DATA >= CASE WHEN :dias = 0 THEN TRUNC(SYSDATE) ELSE SYSDATE - :dias END
  GROUP BY t.TRANSACAO, t.DATA
)
`;

export const STATUS_LABEL: Record<string, string> = {
  L: "1/5 Criada",
  E: "2/5 Em coleta",
  C: "3/5 Em conferência",
  V: "4/5 Em rota",
  T: "5/5 Concluída",
  N: "Cancelada",
};
